;32 bit addition

.MODEL SMALL
.STACK 100H
.DATA
    VAL1 DD 11223344H;
    VAL2 DD 11223344H
    RESULT DW ?
.CODE
    MAIN PROC
        MOV AX, @DATA;
        MOV DS, AX;

        MOV AX, WORD PTR VAL1; LOAD 1ST VALUE FIRST WORD
        MOV BX, WORD PTR VAL2; LOAD 2ND VALUE FIRST WORD
        ADD AX, BX;

        MOV WORD PTR RESULT, AX; MOVE SUM OF RIST WORD TO MEM

        MOV AX, WORD PTR VAL1+2; LOAD SECOND WORD FROM BOTH VALUES
        MOV BX, WORD PTR VAL2+2;

        ADC AX,BX; ADD WITH CARRY (SECOND WORD)

        MOV WORD PTR RESULT+2, AX; MOV SECOND WORD RESULT TO MEM

        MOV DL, 00H; USED FOR FINAL CARRY
        JNC ADDCARY; JUMP TO ADDCARY IF CARRY IS 0
        INC DL;
ADDCARY: 
        MOV BYTE PTR RESULT+4, DL; MOVE FINAL CARRY
        
        MOV AH, 4CH;
        INT 21H
    MAIN ENDP
END MAIN